### ISSUE TITLE
[RTOS] Convert STM32CubeMX Generated Code to FreeRTOS

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/ProteusMC#41]
### Description

Currently, we're using auto-generated code from MCSDK to run our dev kit. We need to port this code to FreeRTOS so that we can integrate it with the rest of our code to verify that everything we're making actually works with hardware. This ticket is to figure out how we can actually do that using the STM MCSDK and STM32CubeMX by configuring the project to use FreeRTOS

Here are the parts the devkit is using for reference:
https://www.st.com/en/evaluation-tools/nucleo-f103rb.html
https://www.digikey.com/en/products/detail/stmicroelectronics/X-NUCLEO-IHM07M1/5492161

### Acceptance Criteria

Code is ported over to FreeRTOS in a way that's actual useable to test our stuff on the devkit

### Proposed Solution

See links above

**Comment by RChandler234** [comment]
ADC and timer are super tightly coupled in the auto-gen code, hard to separate even at a high level. Gate Driver should take the SVGEN Stuff, should take in alpha and beta, so we can calculate sector, duty cycle, and timer values since there so tightly coupled. This way, the gate driver can use those values to configure the ADC for it's next value collection.

Timer interrupt starts up ADC again, so where do we put that logic

Gate Driver SV PWM and 3-phase inverter

**Comment by nwdepatie** [comment]
This was done for our final project for a class
