### ISSUE TITLE
[Driver] - Driving IGBT PWM

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/ProteusMC#8]
### Current Features

Linked to #3 

### Desired Additional Features

We need to fill in the Drive interface and actually configure the PWM of the STM32 to output the signal to the IGBTs. Don't worry about the actual signal yet, just send a duty cycle. Ideally the duty cycle has a fairly high resolution such that we can more finely tune it, 16 bit is probably good but should at least be higher than 8 bit

**Comment by nwdepatie** [comment]
Additionally, use this data type as a parameter to set the PWM, and make it one function that sets all PWM duty cycles in one go with a Master + 2 slave configuration
```typedef struct {
    uint16_t duty_cycles[NUM_PHASES];
} phase_ctrl_dty_t;```

**Comment by MandarinPine18** [comment]
That can be done with just one timer, implementing that.
